# Generated by Django 3.2.5 on 2021-07-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodcreator', '0002_auto_20210719_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodcreator.category', verbose_name='категория'),
        ),
    ]
