# Generated by Django 3.2.5 on 2021-07-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodcreator', '0003_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='goodcreator.category', verbose_name='категория'),
        ),
    ]
