# Generated by Django 3.2.5 on 2021-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodcreator', '0004_auto_20210719_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='is_archive',
        ),
        migrations.AddField(
            model_name='category',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='архив'),
        ),
        migrations.AddField(
            model_name='entry',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='архив'),
        ),
    ]
